In [8]:
# Time.......
import numpy as np
import time
# nd array ka syntax me list () me enclose hoti hai


# python list
size = 1_000_000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"time {end - start}")



# numpy array

numpyarray = np.array(py_list)
start = time.time()
sq_arr = numpyarray**2
end = time.time()
print(f"time {end - start}")


time 0.040258169174194336
time 0.001077890396118164


In [12]:
# memory


import sys

print(f"python list size {sys.getsizeof(py_list)* len(py_list)} bytes")
print(f"python list size {numpyarray.nbytes} bytes")


python list size 8000056000000 bytes
python list size 8000000 bytes


In [24]:
import numpy as np

#  creating and seeting operations on numpy 

arr1 = np.array([1,23,4,5,5])
print(arr1, type(arr1) , arr1.shape , arr1.dtype)

arr2 = np.array([1,23,4,5,5, "Hisvish"])
print(arr2, type(arr2) , arr2.shape , arr2.dtype)


arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, type(arr2d) , arr2d.shape , arr2d.dtype)



[ 1 23  4  5  5] <class 'numpy.ndarray'> (5,) int64
['1' '23' '4' '5' '5' 'Hisvish'] <class 'numpy.ndarray'> (6,) <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3) int64


In [34]:
arr = np.zeros((2,3))
print(arr, type(arr), arr.shape)

arr = np.ones((2,3)) 
print(arr, type(arr), arr.shape)

arr = np.full((2,3), 23)
print(arr, type(arr), arr.shape)

arr = np.eye((2))                       # identity  array
print(arr, type(arr), arr.shape) 

arr = np.arange(1,11, 2)                # evenly diff array
print(arr, type(arr), arr.shape)

arr = np.linspace(1,100,3)              # evenly spaced array
print(arr, type(arr), arr.shape)



[[0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'> (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'> (2, 3)
[[23 23 23]
 [23 23 23]] <class 'numpy.ndarray'> (2, 3)
[[1. 0.]
 [0. 1.]] <class 'numpy.ndarray'> (2, 2)
[1 3 5 7 9] <class 'numpy.ndarray'> (5,)
[  1.   50.5 100. ] <class 'numpy.ndarray'> (3,)


In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,9,8]])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)


# type casting 

float_arr= arr.astype(np.float64)
print(float_arr, type(float_arr))

 

(4, 3)
12
2
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]
 [0. 9. 8.]] <class 'numpy.ndarray'>


In [48]:
arr = np.array([[23,4,5],[43,23,5]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

[[23  4  5]
 [43 23  5]] (2, 3)
[[23  4]
 [ 5 43]
 [23  5]] (3, 2)


In [ ]:
# Data types




In [65]:
# Multidimention 

arry2d = np.array([[2,3],[4,5],[5,7]])
print(arry2d)

print(np.sum(arry2d))

sumofcol = np.sum(arry2d, axis=0)
print(sumofcol)

sumofrow = np.sum(arry2d, axis=1)
print(sumofrow)

print(arry2d[0:1,0:1])

[[2 3]
 [4 5]
 [5 7]]
26
[11 15]
[ 5  9 12]
[[2]]


In [70]:
arr3d = np.array([[[1,2,4],[3,4,6],[6,5,3]],[[6,3,3],[2,4,6],[5,3,1]]])    #2x3x2
print(arr3d)   

print(arr3d[0,1,1])

# slicing
arr3d[:,1,:] =99
print(arr3d)


[[[1 2 4]
  [3 4 6]
  [6 5 3]]

 [[6 3 3]
  [2 4 6]
  [5 3 1]]]
4
[[[ 1  2  4]
  [99 99 99]
  [ 6  5  3]]

 [[ 6  3  3]
  [99 99 99]
  [ 5  3  1]]]


In [73]:
arr = np.array([[2,3],[4,5]])
mean=np.mean(arr)
std_Dev=np.mean(arr)
print((arr-mean)/std_Dev)

 
 

[[-0.42857143 -0.14285714]
 [ 0.14285714  0.42857143]]


In [6]:
#  pandas
import numpy as np
import pandas as pd

country = ["SERS","AEFZVDAW","AEFSVEFZD"]

pd.Series(country)


marks = [2,3,4,4]
subject = ["AEFES","aezfs", "AEF","rbxf",]
pd.Series(marks, index=subject, name= "Vishal marks")

AEFES    2
aezfs    3
AEF      4
rbxf     4
Name: Vishal marks, dtype: int64

In [47]:
import pandas as pd 
import numpy as np 

# result = pd.read_csv('/Users/vishalyadav/Documents/College/Full_STACK_AI/AI_Eng/pandas/subs.csv')
# result = pd.read_csv('/Users/vishalyadav/Documents/College/Full_STACK_AI/AI_Eng/pandas/kohli_ipl.csv', index_col= 'match_no')
result = pd.read_csv('/Users/vishalyadav/Documents/College/Full_STACK_AI/AI_Eng/pandas/bollywood.csv', index_col='movie')



final = result.squeeze()   # 👈 parentheses lagao
print(final)



movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...       
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object
